### ISSUE TITLE
Improved Microsoft instructions

### ISSUE THREAD

**Issue by Xenoxo** [RecastAI/bot-microsoft-connector#1]
There are 2 places that could help clarify with the steps after going through them:

When a person signs up through Microsoft's Application Registration portal, they have to select a "password". However in the instructions config.js file you are asking for a "secret" (which I understand many other places use)

For absolute beginners it helps them to understand that you need to cd into the repository before running the "npm run start" command

Cheers!

**Comment by hcherchi** [comment]
Hey Tim,
You're actually right, I'm going to change it ASAP ;)
thanks for the feedback!
